#!/bin/sh

echo '-----> Checking out Main..'
git checkout main

echo '-----> Pulling from Origin into Main..'
git pull

echo '-----> Deleting Local Remote Branches..'
git fetch -p

echo '-----> Deleting Local Branches..'
git branch --merged | grep -v "\*" | xargs -n 1 git branch -d
