#!/bin/sh

echo '-----> Pulling from Origin into Master..'
git pull

echo '-----> Deleting Local Remote Branches..'
git fetch -p

echo '-----> Deleting Local Branches..'
git branch --merged | grep -v "\*" | xargs -n 1 git branch -d

echo '-----> Bundling..'
bundle -j4

echo '-----> Migrating..'
rake db:migrate
